services:
  - type: worker
    name: telegram-trading-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m playwright install"
    startCommand: "python tradingsignalbot.py"
